# Generated by Django 4.0.2 on 2022-03-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_delete_registration'),
        ('user', '0002_alter_child_join_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='registered_buses',
            field=models.ManyToManyField(blank=True, related_name='childs', to='bus.Bus'),
        ),
    ]
