# Generated by Django 3.2.8 on 2021-12-02 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_type', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_buses', to='bus.bus', verbose_name='bus')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weather', models.CharField(max_length=100)),
                ('wind_speed', models.FloatField()),
                ('date', models.DateTimeField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_bus', to='bus.bus', verbose_name='bus')),
                ('marshal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_route', to='bus.route', verbose_name='route')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_buses', to='bus.bus', verbose_name='bus')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.IntegerField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(max_length=100)),
                ('incident_date_time', models.DateTimeField()),
                ('restart_date_time', models.DateTimeField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('incident_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_location', to='bus.location', verbose_name='location')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_ride', to='bus.ride', verbose_name='ride')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date_time', models.DateTimeField()),
                ('route', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attend_end_location', to='bus.location', verbose_name='location')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attend_ride', to='bus.ride', verbose_name='ride')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attend_start_location', to='bus.location', verbose_name='location')),
            ],
        ),
    ]
