# Generated by Django 4.0.2 on 2022-02-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='country',
            new_name='county',
        ),
    ]
