# Generated by Django 4.0.2 on 2022-03-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_rename_country_bus_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='user_id',
            new_name='user',
        ),
    ]
