# Generated by Django 4.0.2 on 2022-03-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_rename_user_id_registration_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
