# Generated by Django 4.0.2 on 2022-03-09 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_alter_route_locations_alter_route_route_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='locations',
            new_name='places',
        ),
        migrations.AlterField(
            model_name='routeindex',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_index_location', to='bus.location', verbose_name='route_index_location'),
        ),
    ]
