# Generated by Django 4.0.2 on 2022-03-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_rename_locations_route_places_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_name',
            field=models.CharField(default='route name', max_length=100),
            preserve_default=False,
        ),
    ]
