# Generated by Django 4.0.2 on 2022-03-15 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus', '0008_route_route_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='marshal_id',
            new_name='marshal',
        ),
        migrations.AddField(
            model_name='bus',
            name='default_marshal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
