# Generated by Django 4.0.2 on 2022-03-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_alter_ride_date_alter_ride_ride_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='ride',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
