# Generated by Django 4.0.2 on 2022-03-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_rename_date_ride_start_ride_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='places',
            new_name='locations',
        ),
    ]
