# Generated by Django 4.0.2 on 2022-03-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0012_rename_places_route_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
