# Generated by Django 4.0.2 on 2022-04-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0014_alter_location_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_location',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ride_current_location', to='bus.location', verbose_name='ride_current_location'),
            preserve_default=False,
        ),
    ]
