# Generated by Django 4.0.2 on 2022-04-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0015_ride_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='current_location',
            field=models.CharField(max_length=100),
        ),
    ]
