# Generated by Django 4.0.2 on 2022-04-08 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0016_alter_ride_current_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='start_date_time',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='route',
            new_name='join_geo',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_location',
        ),
        migrations.AddField(
            model_name='attendance',
            name='join_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 18, 9, 46, 382223, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='join_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attend_start_location', to='bus.location', verbose_name='location'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default=datetime.datetime(2022, 4, 8, 18, 9, 58, 401083, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
