# Generated by Django 4.0.2 on 2022-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0017_rename_start_date_time_attendance_end_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='join_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
