# Generated by Django 4.0.2 on 2022-04-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0018_alter_attendance_end_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='join_geo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
